Repository escapeSparta/escapeSparta, pull requests merged in 2024-08, with the labels that each got.

#66 feature: cors, web config 추가
  escape-core/src/main/java/com/sparta/config/CorsConfig.java
  escape-core/src/main/java/com/sparta/config/WebConfig.java
  escape-search/src/main/java/com/sparta/config/CorsConfig.java
  escape-search/src/main/java/com/sparta/config/WebConfig.java
  escape-search/src/main/java/com/sparta/domain/store/dto/StoreResponseDto.java
  settings.gradle
Labels: feature

#70 feature : #65 프론트, 백엔드 설정
  escape-core/src/main/java/com/sparta/config/CorsConfig.java
  escape-core/src/main/java/com/sparta/config/SecurityConfig.java
  escape-core/src/main/java/com/sparta/domain/store/entity/StoreRegion.java
  escape-core/src/main/java/com/sparta/domain/theme/entity/ThemeTime.java
  escape-core/src/main/java/com/sparta/domain/theme/entity/ThemeTimeStatus.java
  escape-core/src/main/java/com/sparta/domain/theme/repository/ThemeTimeRepositoryImpl.java
  escape-core/src/main/java/com/sparta/global/util/LocalDateTimeUtil.java
  escape-reservation/src/main/java/com/sparta/domain/kakaopayment/service/PaymentService.java
  escape-reservation/src/main/java/com/sparta/domain/reservation/service/ReservationRequestService.java
  escape-reservation/src/main/java/com/sparta/domain/reservation/service/ReservationService.java
  escape-search/src/main/java/com/sparta/config/CorsConfig.java
  escape-search/src/main/java/com/sparta/controller/SearchController.java
  escape-search/src/main/java/com/sparta/domain/theme/dto/KafkaThemeTimeRequestDto.java
  escape-search/src/main/java/com/sparta/domain/theme/dto/ThemeInfoResponseDto.java
  escape-search/src/main/java/com/sparta/domain/theme/dto/ThemeTimeResponseDto.java
  escape-search/src/main/java/com/sparta/domain/theme/service/ThemeConsumerService.java
  escape-search/src/main/java/com/sparta/domain/theme/service/ThemeService.java
  escape-search/src/main/resources/application.yml
  http-test/ThemeTimeTest.http
  http-test/UserTest.http
  http-test/seongkyun/ReservationTest.http
  http-test/seongkyun/SearchTest.http
Labels: feature

#71 refactor : 프론트 리뷰 게시판 연동 엔티티 수정
  escape-search/src/main/java/com/sparta/domain/review/dto/ReviewResponseDto.java
Labels: refactor

#72 [FEATURE] README 초안 작성
  README.md
Labels: feature

#78 Feature/27 reservation
  escape-reservation/src/main/java/com/sparta/domain/reservation/service/ReservationRequestService.java
  http-test/seongkyun/SearchTest.http
Labels: feature

#79 Fix/76 응답 코드 수정
  escape-core/src/main/java/com/sparta/global/exception/errorCode/SecurityErrorCode.java
Labels: fix

#80 Fix/76 기타 수정
  escape-core/src/main/java/com/sparta/domain/follow/repository/FollowRepositoryImpl.java
  escape-core/src/main/java/com/sparta/global/exception/errorCode/SecurityErrorCode.java
Labels: fix

#83 refactor : 필요없는 kafkaListener 제거
  escape-reservation/src/main/java/com/sparta/config/ConcurrentHashMapConfig.java
  escape-search/src/main/java/com/sparta/config/ConcurrentHashMapConfig.java
  escape-search/src/main/java/com/sparta/domain/review/service/ReviewConsumerService.java
  escape-search/src/main/java/com/sparta/domain/review/service/ReviewService.java
  escape-search/src/main/java/com/sparta/domain/store/service/StoreConsumerService.java
  escape-search/src/main/java/com/sparta/domain/store/service/StoreService.java
  escape-search/src/main/java/com/sparta/domain/theme/service/ThemeConsumerService.java
  escape-search/src/main/java/com/sparta/domain/theme/service/ThemeService.java
Labels: feature

#87 Refactor/85 modules refactor
  escape-consumer/src/main/java/com/sparta/domain/consumer/controller/ConsumerController.java
  escape-consumer/src/main/java/com/sparta/domain/follow/controller/FollowController.java
  escape-consumer/src/main/java/com/sparta/domain/follow/service/FollowService.java
  escape-consumer/src/main/java/com/sparta/domain/review/dto/ReviewCreateRequestDto.java
  escape-consumer/src/main/java/com/sparta/domain/review/dto/ReviewCreateResponseDto.java
  escape-consumer/src/main/java/com/sparta/domain/review/dto/ReviewUpdateRequestDto.java
  escape-consumer/src/main/java/com/sparta/domain/review/dto/ReviewUpdateResponseDto.java
  escape-consumer/src/main/java/com/sparta/domain/review/service/ReviewService.java
  escape-consumer/src/main/java/com/sparta/feign/EscapeReservationClient.java
  escape-core/src/main/java/com/sparta/global/exception/customException/KafkaException.java
  escape-core/src/main/java/com/sparta/global/exception/errorCode/KafkaErrorCode.java
  escape-reservation/src/main/java/com/sparta/domain/kafka/kafkaEmailService/AmazonSESService.java
  escape-reservation/src/main/java/com/sparta/domain/kafka/kafkaEmailService/KafkaEmailConsumer.java
  escape-reservation/src/main/java/com/sparta/domain/kafka/kafkaEmailService/KafkaEmailProducer.java
  escape-reservation/src/main/java/com/sparta/domain/reservation/service/ReservationRequestService.java
  escape-reservation/src/main/java/com/sparta/domain/reservation/service/ReservationService.java
  escape-search/src/main/java/com/sparta/domain/review/service/ReviewConsumerService.java
  escape-search/src/main/java/com/sparta/domain/review/service/ReviewService.java
  escape-search/src/main/java/com/sparta/domain/store/service/StoreConsumerService.java
  escape-search/src/main/java/com/sparta/domain/store/service/StoreService.java
  escape-search/src/main/java/com/sparta/domain/theme/service/ThemeConsumerService.java
  escape-search/src/main/java/com/sparta/domain/theme/service/ThemeService.java
  http-test/seongkyun/ReservationTest.http
Labels: refactor

#93 Refactor/92 kafka
  escape-reservation/src/main/java/com/sparta/config/KafkaConsumerConfig.java
  escape-reservation/src/main/java/com/sparta/config/KafkaProducerConfig.java
  escape-reservation/src/main/java/com/sparta/domain/reservation/service/ReservationRequestService.java
  escape-reservation/src/main/java/com/sparta/kafkaError/KafkaErrorHandler.java
  escape-search/src/main/java/com/sparta/config/KafkaConsumerConfig.java
  escape-search/src/main/java/com/sparta/config/KafkaProducerConfig.java
  escape-search/src/main/java/com/sparta/domain/review/dto/KafkaReviewRequestDto.java
  escape-search/src/main/java/com/sparta/domain/review/service/ReviewConsumerService.java
  escape-search/src/main/java/com/sparta/domain/store/service/StoreConsumerService.java
  escape-search/src/main/java/com/sparta/domain/store/service/StoreService.java
  escape-search/src/main/java/com/sparta/domain/theme/service/ThemeConsumerService.java
  escape-search/src/main/java/com/sparta/domain/theme/service/ThemeService.java
  escape-search/src/main/java/com/sparta/kafkaError/KafkaErrorHandler.java
  escape-search/src/test/java/com/sparta/domain/store/service/TestStoreService.java
  escape-search/src/test/java/domain/store/service/StoreConsumerServiceTestService.java
  escape-search/src/test/java/domain/store/service/StoreServiceTest.java
  http-test/seongkyun/ReservationTest.http
Labels: refactor

#101 Test/88 seongkyun 테스트코드
  escape-consumer/src/test/java/consumer/ConsumerServiceTest.java
  escape-consumer/src/test/java/follow/FollowServiceTest.java
  escape-consumer/src/test/java/review/ReviewServiceTest.java
  escape-core/src/main/java/com/sparta/global/kafka/KafkaTopic.java
  escape-reservation/src/main/java/com/sparta/domain/kakaopayment/service/PaymentService.java
  escape-search/src/test/java/com/sparta/domain/store/service/StoreConsumerServiceTestService.java
  escape-search/src/test/java/com/sparta/domain/store/service/StoreServiceTest.java
  escape-search/src/test/java/domain/store/service/StoreServiceTest.java
Labels: test

#104 Feature/102 인기테마 조회 테마 추천
  escape-admin/src/main/java/com/sparta/domain/reservation/dto/ReservationsGetResponseDto.java
  escape-admin/src/main/java/com/sparta/domain/user/service/UserAdminService.java
  escape-consumer/src/main/java/com/sparta/domain/follow/controller/FollowController.java
  escape-consumer/src/main/java/com/sparta/domain/recommendation/controller/RecommendationController.java
  escape-consumer/src/main/java/com/sparta/domain/recommendation/service/RecommendationService.java
  escape-consumer/src/main/java/com/sparta/domain/review/service/ReviewService.java
  escape-core/src/main/java/com/sparta/config/WebConfig.java
  escape-core/src/main/java/com/sparta/domain/recommendation/entity/Recommendation.java
  escape-core/src/main/java/com/sparta/domain/recommendation/repository/RecommendationCustom.java
  escape-core/src/main/java/com/sparta/domain/recommendation/repository/RecommendationCustomImpl.java
  escape-core/src/main/java/com/sparta/domain/recommendation/repository/RecommendationRepository.java
  escape-core/src/main/java/com/sparta/domain/store/repository/StoreRepositoryCustom.java
  escape-core/src/main/java/com/sparta/domain/store/repository/StoreRepositoryImpl.java
  escape-core/src/main/java/com/sparta/domain/user/dto/request/WithdrawRequestDto.java
  escape-core/src/main/java/com/sparta/domain/user/dto/response/SignupResponseDto.java
  escape-core/src/main/java/com/sparta/global/entity/TimeStamped.java
  escape-core/src/main/java/com/sparta/global/exception/customException/RecommendationException.java
  escape-core/src/main/java/com/sparta/global/exception/errorCode/RecommendationErrorCode.java
  escape-core/src/main/java/com/sparta/global/jwt/JwtProvider.java
  escape-core/src/main/java/com/sparta/global/jwt/RefreshTokenService.java
  escape-core/src/main/java/com/sparta/global/kafka/KafkaTopic.java
  escape-core/src/main/java/com/sparta/global/security/filter/JwtAuthenticationFilter.java
  escape-core/src/main/java/com/sparta/global/util/LocalDateTimeUtil.java
  escape-core/src/main/java/com/sparta/global/util/ResponseUtil.java
  escape-reservation/src/main/java/com/sparta/domain/kakaopayment/controller/PaymentController.java
  escape-reservation/src/main/java/com/sparta/domain/reservation/service/ReservationService.java
  escape-search/src/main/java/com/sparta/config/ConcurrentHashMapConfig.java
  escape-search/src/main/java/com/sparta/controller/SearchController.java
  escape-search/src/main/java/com/sparta/domain/review/service/ReviewService.java
  escape-search/src/main/java/com/sparta/domain/store/dto/KafkaTopStoreRequestDto.java
  escape-search/src/main/java/com/sparta/domain/store/dto/KafkaTopStoreResponseDto.java
  escape-search/src/main/java/com/sparta/domain/store/dto/TopStoreResponseDto.java
  escape-search/src/main/java/com/sparta/domain/store/service/StoreConsumerService.java
  escape-search/src/main/java/com/sparta/domain/store/service/StoreService.java
  escape-search/src/main/java/com/sparta/domain/theme/dto/ThemeInfoResponseDto.java
  escape-search/src/main/java/com/sparta/domain/theme/service/ThemeConsumerService.java
  escape-search/src/main/java/com/sparta/domain/theme/service/ThemeService.java
  escape-search/src/test/java/com/sparta/domain/store/service/StoreConsumerServiceTestService.java
  escape-search/src/test/java/com/sparta/domain/store/service/StoreServiceTest.java
  http-test/seongkyun/RecommendationTest.http
  http-test/seongkyun/SearchTest.http
Labels: feature

#107 Fix/106 top-store 수정
  escape-core/src/main/java/com/sparta/domain/store/repository/StoreRepositoryImpl.java
Labels: fix

#99 test : 인증/인가 테스트 코드
  escape-core/src/main/java/com/sparta/domain/user/dto/request/SignupRequestDto.java
  escape-core/src/main/java/com/sparta/domain/user/dto/request/WithdrawRequestDto.java
  escape-core/src/test/java/UserTest.java
Labels: feature

#110 Feature/61 Redis caching
  create-topic.sh
  escape-core/src/main/java/com/sparta/config/RedisConfig.java
  escape-core/src/main/java/com/sparta/global/kafka/KafkaTopic.java
  escape-search/src/main/java/com/sparta/config/ConcurrentHashMapConfig.java
  escape-search/src/main/java/com/sparta/controller/SearchController.java
  escape-search/src/main/java/com/sparta/domain/store/dto/KafkaTopStoreResponseDto.java
  escape-search/src/main/java/com/sparta/domain/store/dto/StoreDetailResponseDto.java
  escape-search/src/main/java/com/sparta/domain/store/dto/TopStoreResponseDto.java
  escape-search/src/main/java/com/sparta/domain/store/service/StoreConsumerService.java
  escape-search/src/main/java/com/sparta/domain/store/service/StoreService.java
  escape-search/src/main/resources/application.yml
Labels: feature

#115 Documentation/111 manager, admin
  escape-admin/Dockerfile
  escape-admin/src/main/java/com/sparta/domain/reservation/controller/ReservationAdminController.java
  escape-admin/src/main/java/com/sparta/domain/reservation/service/ReservationAdminService.java
  escape-admin/src/main/java/com/sparta/domain/review/controller/ReviewAdminController.java
  escape-admin/src/main/java/com/sparta/domain/review/service/ReviewAdminService.java
  escape-admin/src/main/java/com/sparta/domain/store/controller/StoreAdminController.java
  escape-admin/src/main/java/com/sparta/domain/store/service/StoreAdminService.java
  escape-admin/src/main/java/com/sparta/domain/theme/controller/ThemeAdminController.java
  escape-admin/src/main/java/com/sparta/domain/theme/controller/ThemeTimeAdminController.java
  escape-admin/src/main/java/com/sparta/domain/theme/service/ThemeAdminService.java
  escape-admin/src/main/java/com/sparta/domain/theme/service/ThemeTimeAdminService.java
  escape-admin/src/main/java/com/sparta/domain/user/controller/UserAdminController.java
  escape-admin/src/main/java/com/sparta/domain/user/service/UserAdminService.java
  escape-consumer/Dockerfile
  escape-consumer/src/main/java/com/sparta/domain/ConsumerStatusController.java
  escape-core/Dockerfile
  escape-core/src/main/java/com/sparta/domain/reservation/entity/Reservation.java
  escape-manager/Dockerfile
  escape-manager/src/main/java/com/sparta/domain/ManagerStatusController.java
  escape-manager/src/main/java/com/sparta/domain/reservation/controller/ReservationController.java
  escape-manager/src/main/java/com/sparta/domain/reservation/service/ReservationService.java
  escape-manager/src/main/java/com/sparta/domain/s3/S3Uploader.java
  escape-manager/src/main/java/com/sparta/domain/s3/S3Util.java
  escape-manager/src/main/java/com/sparta/domain/store/controller/StoreController.java
  escape-manager/src/main/java/com/sparta/domain/store/service/StoreService.java
  escape-manager/src/main/java/com/sparta/domain/theme/controller/ThemeController.java
  escape-manager/src/main/java/com/sparta/domain/theme/controller/ThemeTimeController.java
  escape-manager/src/main/java/com/sparta/domain/theme/service/ThemeService.java
  escape-manager/src/main/java/com/sparta/domain/theme/service/ThemeTimeService.java
  escape-reservation/Dockerfile
  escape-reservation/src/main/java/com/sparta/domain/kakaopayment/service/PaymentService.java
  escape-search/Dockerfile
Labels: documentation

#116 documentation : #113 javadoc 주석 추가
  escape-search/src/main/java/com/sparta/controller/SearchController.java
  escape-search/src/main/java/com/sparta/controller/SearchStatusController.java
  escape-search/src/main/java/com/sparta/domain/review/service/ReviewConsumerService.java
  escape-search/src/main/java/com/sparta/domain/store/service/StoreConsumerService.java
  escape-search/src/main/java/com/sparta/domain/store/service/StoreService.java
  escape-search/src/main/java/com/sparta/domain/theme/service/ThemeConsumerService.java
Labels: documentation

#119 118-documentation-core
  escape-core/src/main/java/com/sparta/domain/follow/repository/FollowRepositoryImpl.java
  escape-core/src/main/java/com/sparta/domain/payment/repository/PaymentRepositoryImpl.java
  escape-core/src/main/java/com/sparta/domain/recommendation/repository/RecommendationCustomImpl.java
  escape-core/src/main/java/com/sparta/domain/reservation/repository/ReservationRepositoryImpl.java
  escape-core/src/main/java/com/sparta/domain/review/repository/ReviewRepositoryImpl.java
  escape-core/src/main/java/com/sparta/domain/store/repository/StoreRepositoryImpl.java
  escape-core/src/main/java/com/sparta/domain/theme/repository/ThemeRepositoryImpl.java
  escape-core/src/main/java/com/sparta/domain/theme/repository/ThemeTimeRepositoryImpl.java
  escape-core/src/main/java/com/sparta/domain/user/controller/AuthController.java
  escape-core/src/main/java/com/sparta/domain/user/controller/EmailController.java
  escape-core/src/main/java/com/sparta/domain/user/controller/UserController.java
  escape-core/src/main/java/com/sparta/domain/user/service/AuthService.java
  escape-core/src/main/java/com/sparta/domain/user/service/EmailService.java
  escape-core/src/main/java/com/sparta/domain/user/service/UserService.java
Labels: documentation

#122 Bugfix/121 결제 시 검증 수정
  escape-reservation/src/main/java/com/sparta/domain/kakaopayment/service/PaymentService.java
Labels: fix
