Repository escapeSparta/escapeSparta, pull requests merged in 2024-07, with the labels that each got.

#10 Feature/8 admin 기능 구현
  escape-admin/src/main/java/com/sparta/escaperoom/controller/EscapeRoomController.java
  escape-admin/src/main/java/com/sparta/store/controller/StoreController.java
  escape-admin/src/main/java/com/sparta/user/controller/UserController.java
  escape-admin/src/main/java/com/sparta/user/service/UserService.java
  escape-core/src/main/java/com/sparta/domain/review/service/ReviewAdminService.java
  escape-core/src/main/java/com/sparta/domain/store/dto/StoreCreateRequestDto.java
  escape-core/src/main/java/com/sparta/domain/store/dto/StoreResponseDto.java
  escape-core/src/main/java/com/sparta/domain/store/entity/Store.java
  escape-core/src/main/java/com/sparta/domain/store/repository/StoreRepository.java
  escape-core/src/main/java/com/sparta/domain/store/service/StoreAdminService.java
  escape-core/src/main/java/com/sparta/domain/user/dto/UserResponseDto.java
  escape-core/src/main/java/com/sparta/domain/user/repository/UserRepository.java
  escape-core/src/main/java/com/sparta/global/exception/errorCode/StoreErrorCode.java
  escape-core/src/main/java/com/sparta/global/exception/errorCode/UserErrorCode.java
Labels: feature

#12 Feature/3-auth
  build.gradle
  escape-core/src/main/java/com/sparta/config/SecurityConfig.java
  escape-core/src/main/java/com/sparta/domain/theme/entity/Theme.java
  escape-core/src/main/java/com/sparta/domain/user/controller/UserController.java
  escape-core/src/main/java/com/sparta/domain/user/dto/UserResponseDto.java
  escape-core/src/main/java/com/sparta/domain/user/dto/request/LoginRequestDto.java
  escape-core/src/main/java/com/sparta/domain/user/dto/request/SignupRequestDto.java
  escape-core/src/main/java/com/sparta/domain/user/dto/response/SignupResponseDto.java
  escape-core/src/main/java/com/sparta/domain/user/entity/User.java
  escape-core/src/main/java/com/sparta/domain/user/entity/UserStatus.java
  escape-core/src/main/java/com/sparta/domain/user/entity/UserType.java
  escape-core/src/main/java/com/sparta/domain/user/repository/UserRepository.java
  escape-core/src/main/java/com/sparta/domain/user/service/UserService.java
  escape-core/src/main/java/com/sparta/global/exception/errorCode/UserErrorCode.java
  escape-core/src/main/java/com/sparta/jwt/JwtProvider.java
  escape-core/src/main/java/com/sparta/jwt/RefreshToken.java
  escape-core/src/main/java/com/sparta/jwt/RefreshTokenRepository.java
  escape-core/src/main/java/com/sparta/jwt/RefreshTokenService.java
  escape-core/src/main/java/com/sparta/security/JwtAuthenticationFilter.java
  escape-core/src/main/java/com/sparta/security/JwtAuthorizationFilter.java
  escape-core/src/main/java/com/sparta/security/UserDetailsImpl.java
  escape-core/src/main/java/com/sparta/security/UserDetailsServiceImpl.java
  escape-core/src/main/resources/application.yml
  escape-follow/src/main/java/com/sparta/Main.java
  escape-reservation/src/main/java/com/sparta/Main.java
  escape-review/src/main/java/com/sparta/Main.java
  escape-search/src/main/java/com/sparta/Main.java
  escape-store/src/main/java/com/sparta/Main.java
  http-test/UserTest.http
Labels: feature

#24 Feature/21 Themetime 기능 구현
  escape-core/src/main/java/com/sparta/domain/theme/entity/Theme.java
  escape-core/src/main/java/com/sparta/domain/theme/entity/ThemeTime.java
  escape-core/src/main/java/com/sparta/domain/theme/repository/ThemeRepositoryCustom.java
  escape-core/src/main/java/com/sparta/domain/theme/repository/ThemeRepositoryImpl.java
  escape-core/src/main/java/com/sparta/domain/theme/repository/ThemeTimeRepository.java
  escape-core/src/main/java/com/sparta/domain/theme/repository/ThemeTimeRepositoryCustom.java
  escape-core/src/main/java/com/sparta/domain/theme/repository/ThemeTimeRepositoryImpl.java
  escape-core/src/main/java/com/sparta/global/exception/customException/LocalDateTimeException.java
  escape-core/src/main/java/com/sparta/global/exception/customException/ThemeTimeException.java
  escape-core/src/main/java/com/sparta/global/exception/errorCode/LocalDateTimeErrorCode.java
  escape-core/src/main/java/com/sparta/global/exception/errorCode/ThemeTimeErrorCode.java
  escape-core/src/main/java/com/sparta/global/exception/exceptionHandler/GlobalExceptionHandler.java
  escape-core/src/main/java/com/sparta/global/util/LocalDateTimeUtil.java
  escape-search/src/main/java/com/sparta/domain/theme/dto/ThemeInfoResponseDto.java
  escape-store/src/main/java/com/sparta/controller/StoreController.java
  escape-store/src/main/java/com/sparta/controller/ThemeTimeController.java
  escape-store/src/main/java/com/sparta/dto/request/ThemeCreateRequestDto.java
  escape-store/src/main/java/com/sparta/dto/request/ThemeModifyRequestDto.java
  escape-store/src/main/java/com/sparta/dto/request/ThemeTimeCreateRequestDto.java
  escape-store/src/main/java/com/sparta/dto/request/ThemeTimeModifyRequestDto.java
  escape-store/src/main/java/com/sparta/dto/response/StoreDetailResponseDto.java
  escape-store/src/main/java/com/sparta/dto/response/StoreModifyResponseDto.java
  escape-store/src/main/java/com/sparta/dto/response/ThemeDetailResponseDto.java
  escape-store/src/main/java/com/sparta/dto/response/ThemeTimeDetailResponseDto.java
  escape-store/src/main/java/com/sparta/service/StoreService.java
  escape-store/src/main/java/com/sparta/service/ThemeTimeService.java
  escape-store/src/main/resources/application.yml
  http-test/StoreManagerTest.http
  http-test/ThemeManagerTest.http
  http-test/ThemeTimeTest.http
Labels: feature

#25 Feature/20 review
  build.gradle
  escape-core/src/main/java/com/sparta/config/SecurityConfig.java
  escape-core/src/main/java/com/sparta/domain/follow/repository/FollowRepository.java
  escape-core/src/main/java/com/sparta/domain/reaction/entity/Reaction.java
  escape-core/src/main/java/com/sparta/domain/reaction/entity/ReactionType.java
  escape-core/src/main/java/com/sparta/domain/reaction/repository/ReactionRepository.java
  escape-core/src/main/java/com/sparta/domain/reservation/repository/ReservationRepository.java
  escape-core/src/main/java/com/sparta/domain/review/entity/Review.java
  escape-core/src/main/java/com/sparta/domain/review/repository/ReviewRepository.java
  escape-core/src/main/java/com/sparta/domain/review/repository/ReviewRepositoryCustom.java
  escape-core/src/main/java/com/sparta/domain/review/repository/ReviewRepositoryImpl.java
  escape-core/src/main/java/com/sparta/domain/store/entity/StoreStatus.java
  escape-core/src/main/java/com/sparta/domain/store/repository/StoreRepositoryCustom.java
  escape-core/src/main/java/com/sparta/domain/store/repository/StoreRepositoryImpl.java
  escape-core/src/main/java/com/sparta/domain/theme/entity/Theme.java
  escape-core/src/main/java/com/sparta/domain/theme/repository/ThemeRepositoryImpl.java
  escape-core/src/main/java/com/sparta/global/exception/errorCode/ReactionErrorCode.java
  escape-core/src/main/java/com/sparta/global/exception/errorCode/ReservationErrorCode.java
  escape-core/src/main/java/com/sparta/global/exception/errorCode/ReviewErrorCode.java
  escape-core/src/main/java/com/sparta/jwt/RefreshTokenRepository.java
  escape-core/src/main/resources/application.yml
  escape-review/src/main/java/com/sparta/EscapeReviewApplication.java
  escape-review/src/main/java/com/sparta/Main.java
  escape-review/src/main/java/com/sparta/config/JpaConfig.java
  escape-review/src/main/java/com/sparta/domain/review/controller/ReviewController.java
  escape-review/src/main/java/com/sparta/domain/review/dto/CreateReviewRequestDto.java
  escape-review/src/main/java/com/sparta/domain/review/dto/CreateReviewResponseDto.java
  escape-review/src/main/java/com/sparta/domain/review/dto/ReactionRequest.java
  escape-review/src/main/java/com/sparta/domain/review/dto/ReactionResponseDto.java
  escape-review/src/main/java/com/sparta/domain/review/dto/ReviewResponseDto.java
  escape-review/src/main/java/com/sparta/domain/review/dto/UpdateReviewRequestDto.java
  escape-review/src/main/java/com/sparta/domain/review/dto/UpdateReviewResponseDto.java
  escape-review/src/main/java/com/sparta/domain/review/service/ReviewService.java
  escape-review/src/main/resources/application.yml
  escape-search/src/main/java/com/sparta/domain/review/dto/ReviewResponseDto.java
  escape-search/src/main/java/com/sparta/domain/store/dto/StoreResponseDto.java
  escape-search/src/main/java/com/sparta/domain/theme/dto/ThemeInfoResponseDto.java
  escape-search/src/main/java/com/sparta/domain/theme/dto/ThemeResponseDto.java
  escape-search/src/main/java/com/sparta/domain/theme/dto/ThemeTimeResponseDto.java
  http-test/UserTest.http
  http-test/seongkyun/Test.http
Labels: feature

#32 Feature/23 user - 유저 CRUD 기능구현
  escape-consumer/src/main/java/com/sparta/controller/ConsumerController.java
  escape-consumer/src/main/java/com/sparta/dto/request/EditPasswordRequestDto.java
  escape-consumer/src/main/java/com/sparta/dto/request/EditProfileRequestDto.java
  escape-consumer/src/main/java/com/sparta/service/ConsumerService.java
  escape-consumer/src/main/java/config/JpaConfig.java
  escape-consumer/src/main/resources/application.yml
  escape-core/src/main/java/com/sparta/config/RedisConfig.java
  escape-core/src/main/java/com/sparta/domain/user/controller/UserController.java
  escape-core/src/main/java/com/sparta/domain/user/dto/UserResponseDto.java
  escape-core/src/main/java/com/sparta/domain/user/dto/request/WithdrawRequestDto.java
  escape-core/src/main/java/com/sparta/domain/user/entity/User.java
  escape-core/src/main/java/com/sparta/domain/user/entity/UserType.java
  escape-core/src/main/java/com/sparta/domain/user/repository/UserRepository.java
  escape-core/src/main/java/com/sparta/domain/user/service/UserService.java
  escape-core/src/main/java/com/sparta/global/exception/errorCode/UserErrorCode.java
  escape-core/src/main/java/com/sparta/security/UserDetailsImpl.java
Labels: feature

#33 Feature/26 s3
  escape-core/src/main/java/com/sparta/domain/store/entity/Store.java
  escape-core/src/main/java/com/sparta/domain/theme/entity/Theme.java
  escape-core/src/main/java/com/sparta/global/exception/customException/S3Exception.java
  escape-core/src/main/java/com/sparta/global/exception/errorCode/S3ErrorCode.java
  escape-core/src/main/java/com/sparta/global/exception/exceptionHandler/GlobalExceptionHandler.java
  escape-store/build.gradle
  escape-store/src/main/java/com/sparta/config/S3Config.java
  escape-store/src/main/java/com/sparta/controller/StoreController.java
  escape-store/src/main/java/com/sparta/controller/ThemeController.java
  escape-store/src/main/java/com/sparta/dto/response/ThemeDetailResponseDto.java
  escape-store/src/main/java/com/sparta/s3/S3Uploader.java
  escape-store/src/main/java/com/sparta/s3/S3Util.java
  escape-store/src/main/java/com/sparta/service/StoreService.java
  escape-store/src/main/java/com/sparta/service/ThemeService.java
  escape-store/src/main/resources/application.yml
Labels: feature

#37 Feature/36 reservation managed
  escape-core/src/main/java/com/sparta/domain/reservation/entity/Reservation.java
  escape-core/src/main/java/com/sparta/domain/reservation/repository/ReservationRepository.java
  escape-core/src/main/java/com/sparta/domain/reservation/repository/ReservationRepositoryCustom.java
  escape-core/src/main/java/com/sparta/domain/reservation/repository/ReservationRepositoryImpl.java
  escape-reservation/src/main/java/com/sparta/service/ReservationService.java
  escape-store/src/main/java/com/sparta/controller/ReservationController.java
  escape-store/src/main/java/com/sparta/dto/response/ReservationDetailResponseDto.java
  escape-store/src/main/java/com/sparta/dto/response/ReservationsGetResponseDto.java
  escape-store/src/main/java/com/sparta/service/ReservationService.java
  http-test/Reservation.http
Labels: feature

#39 refactor : #38 dependency, yml 파일 등 수정
  build.gradle
  escape-admin/build.gradle
  escape-admin/src/main/java/com/sparta/config/JpaConfig.java
  escape-admin/src/main/java/com/sparta/config/SubModuleConfig.java
  escape-admin/src/main/java/com/sparta/store/controller/StoreController.java
  escape-admin/src/main/java/com/sparta/store/dto/StoreCreateRequestDto.java
  escape-admin/src/main/java/com/sparta/store/dto/StoreResponseDto.java
  escape-admin/src/main/java/com/sparta/store/service/StoreAdminService.java
  escape-admin/src/main/java/com/sparta/user/controller/UserAdminController.java
  escape-admin/src/main/java/com/sparta/user/service/UserAdminService.java
  escape-admin/src/main/resources/application.yml
  escape-consumer/src/main/java/config/JpaConfig.java
  escape-consumer/src/main/java/config/SubModuleConfig.java
  escape-core/build.gradle
  escape-core/src/main/java/com/sparta/config/AppConfig.java
  escape-core/src/main/resources/application.yml
  escape-follow/src/main/java/com/sparta/config/SubModuleConfig.java
  escape-follow/src/main/resources/application.yml
  escape-manager/src/main/java/com/sparta/EscapeManagerApplication.java
  escape-manager/src/main/java/com/sparta/Main.java
  escape-manager/src/main/java/com/sparta/config/JpaConfig.java
  escape-manager/src/main/java/com/sparta/config/PropertyConfig.java
  escape-manager/src/main/java/com/sparta/config/SubModuleConfig.java
  escape-manager/src/main/resources/application.yml
  escape-reservation/src/main/java/config/SubModuleConfig.java
  escape-reservation/src/main/resources/application.yml
  escape-review/src/main/java/com/sparta/config/PropertyConfig.java
  escape-review/src/main/java/com/sparta/config/SubModuleConfig.java
  escape-review/src/main/resources/application.yml
  escape-search/src/main/java/com/sparta/config/PropertyConfig.java
  escape-search/src/main/java/com/sparta/config/SubModuleConfig.java
  escape-search/src/main/resources/application.yml
  escape-store/src/main/java/com/sparta/config/PropertyConfig.java
  escape-store/src/main/java/com/sparta/config/SubModuleConfig.java
  escape-store/src/main/java/com/sparta/service/ThemeService.java
  escape-store/src/main/resources/application.yml
Labels: refactor

#43 Test/41 http test
  escape-core/src/main/java/com/sparta/config/AppConfig.java
  escape-core/src/main/java/com/sparta/config/PropertyConfig.java
  escape-reservation/src/main/java/com/sparta/controller/ReservationController.java
  escape-reservation/src/main/java/com/sparta/dto/ReservationCreateRequestDto.java
  escape-reservation/src/main/java/com/sparta/dto/ReservationCreateResponseDto.java
  escape-reservation/src/main/java/com/sparta/service/ReservationService.java
  escape-reservation/src/main/java/config/JpaConfig.java
  escape-review/src/main/java/com/sparta/domain/review/controller/ReviewController.java
  escape-review/src/main/java/com/sparta/domain/review/dto/ReviewCreateRequestDto.java
  escape-review/src/main/java/com/sparta/domain/review/dto/ReviewCreateResponseDto.java
  escape-review/src/main/java/com/sparta/domain/review/dto/ReviewUpdateRequestDto.java
  escape-review/src/main/java/com/sparta/domain/review/dto/ReviewUpdateResponseDto.java
  escape-review/src/main/java/com/sparta/domain/review/service/ReviewService.java
  escape-search/src/main/java/com/sparta/controller/SearchController.java
  http-test/seongkyun/FollowTest.http
  http-test/seongkyun/ReservationTest.http
  http-test/seongkyun/ReviewTest.http
  http-test/seongkyun/SearchTest.http
Labels: test

#44 Test/40 store 모듈 관련 http 테스트 추가
  escape-store/src/main/java/com/sparta/controller/ThemeController.java
  escape-store/src/main/java/com/sparta/dto/response/ThemeDetailResponseDto.java
  http-test/Reservation.http
  http-test/ReservationTest.http
  http-test/StoreAdminTest.http
  http-test/StoreManagerTest.http
  http-test/ThemeManagerTest.http
  http-test/ThemeTimeTest.http
Labels: test

#45 test : #41 예약, 조회 테스트 추가
  http-test/seongkyun/ReservationTest.http
  http-test/seongkyun/ReviewTest.http
  http-test/seongkyun/SearchTest.http
Labels: test

#50 Refactor/49 review follow 병합
  escape-consumer/src/main/java/com/sparta/config/PropertyConfig.java
  escape-consumer/src/main/java/com/sparta/config/SubModuleConfig.java
  escape-consumer/src/main/java/com/sparta/domain/consumer/controller/ConsumerController.java
  escape-consumer/src/main/java/com/sparta/domain/consumer/dto/CreateReservationRequestDto.java
  escape-consumer/src/main/java/com/sparta/domain/consumer/dto/request/EditPasswordRequestDto.java
  escape-consumer/src/main/java/com/sparta/domain/consumer/dto/request/EditProfileRequestDto.java
  escape-consumer/src/main/java/com/sparta/domain/consumer/service/ConsumerService.java
  escape-consumer/src/main/java/com/sparta/domain/follow/controller/FollowController.java
  escape-consumer/src/main/java/com/sparta/domain/follow/dto/FollowStoreResponseDto.java
  escape-consumer/src/main/java/com/sparta/domain/follow/service/FollowService.java
  escape-consumer/src/main/java/com/sparta/domain/review/controller/ReviewController.java
  escape-consumer/src/main/java/com/sparta/domain/review/dto/ReactionRequest.java
  escape-consumer/src/main/java/com/sparta/domain/review/dto/ReactionResponseDto.java
  escape-consumer/src/main/java/com/sparta/domain/review/dto/ReviewCreateRequestDto.java
  escape-consumer/src/main/java/com/sparta/domain/review/dto/ReviewCreateResponseDto.java
  escape-consumer/src/main/java/com/sparta/domain/review/dto/ReviewResponseDto.java
  escape-consumer/src/main/java/com/sparta/domain/review/dto/ReviewUpdateRequestDto.java
  escape-consumer/src/main/java/com/sparta/domain/review/dto/ReviewUpdateResponseDto.java
  escape-consumer/src/main/java/com/sparta/domain/review/service/ReviewService.java
  escape-consumer/src/main/java/config/SubModuleConfig.java
  escape-follow/build.gradle
  escape-follow/src/main/java/com/sparta/EscapeFollowApplication.java
  escape-follow/src/main/resources/application.yml
  escape-review/build.gradle
  escape-review/src/main/java/com/sparta/EscapeReviewApplication.java
  escape-review/src/main/java/com/sparta/config/SubModuleConfig.java
  escape-review/src/main/resources/application.yml
  http-test/seongkyun/FollowTest.http
  http-test/seongkyun/ReviewTest.http
  settings.gradle
Labels: refactor

#55 Feature/23 user - 관리자 회원가입
  escape-core/src/main/java/com/sparta/config/EmailConfig.java
  escape-core/src/main/java/com/sparta/config/RedisConfig.java
  escape-core/src/main/java/com/sparta/config/SecurityConfig.java
  escape-core/src/main/java/com/sparta/domain/user/controller/EmailController.java
  escape-core/src/main/java/com/sparta/domain/user/controller/UserController.java
  escape-core/src/main/java/com/sparta/domain/user/dto/request/InviteRequestDto.java
  escape-core/src/main/java/com/sparta/domain/user/dto/request/SignupRequestDto.java
  escape-core/src/main/java/com/sparta/domain/user/entity/User.java
  escape-core/src/main/java/com/sparta/domain/user/repository/UserRepository.java
  escape-core/src/main/java/com/sparta/domain/user/service/EmailService.java
  escape-core/src/main/java/com/sparta/domain/user/service/UserService.java
  escape-core/src/main/resources/application.yml
Labels: feature

#57 Refactor/56 signup email
  escape-core/src/main/java/com/sparta/domain/user/controller/EmailController.java
  escape-core/src/main/java/com/sparta/domain/user/controller/UserController.java
  escape-core/src/main/java/com/sparta/domain/user/dto/request/CertificateRequestDto.java
  escape-core/src/main/java/com/sparta/domain/user/dto/request/EmailVerificationRequestDto.java
  escape-core/src/main/java/com/sparta/domain/user/dto/request/InviteRequestDto.java
  escape-core/src/main/java/com/sparta/domain/user/dto/request/SignupRequestDto.java
  escape-core/src/main/java/com/sparta/domain/user/entity/User.java
  escape-core/src/main/java/com/sparta/domain/user/repository/EmailRepository.java
  escape-core/src/main/java/com/sparta/domain/user/repository/UserRepository.java
  escape-core/src/main/java/com/sparta/domain/user/service/EmailService.java
  escape-core/src/main/java/com/sparta/domain/user/service/UserService.java
  escape-core/src/main/java/com/sparta/global/exception/errorCode/EmailErrorCode.java
  escape-core/src/main/java/com/sparta/global/exception/errorCode/UserErrorCode.java
  escape-core/src/main/java/com/sparta/security/JwtAuthenticationFilter.java
  escape-core/src/main/resources/application.yml
  escape-manager/src/main/resources/application.yml
  http-test/UserTest.http
Labels: refactor

#60 Feature/58 Refresh token with redis
  escape-core/src/main/java/com/sparta/config/RedisConfig.java
  escape-core/src/main/java/com/sparta/config/SecurityConfig.java
  escape-core/src/main/java/com/sparta/domain/user/controller/AuthController.java
  escape-core/src/main/java/com/sparta/domain/user/repository/EmailRepository.java
  escape-core/src/main/java/com/sparta/domain/user/service/AuthService.java
  escape-core/src/main/java/com/sparta/domain/user/service/UserService.java
  escape-core/src/main/java/com/sparta/global/exception/customException/AuthException.java
  escape-core/src/main/java/com/sparta/global/exception/customException/CustomSecurityException.java
  escape-core/src/main/java/com/sparta/global/exception/errorCode/AuthErrorCode.java
  escape-core/src/main/java/com/sparta/global/exception/errorCode/CommonErrorCode.java
  escape-core/src/main/java/com/sparta/global/exception/errorCode/RefreshTokenErrorCode.java
  escape-core/src/main/java/com/sparta/global/exception/errorCode/SecurityErrorCode.java
  escape-core/src/main/java/com/sparta/jwt/JwtProvider.java
  escape-core/src/main/java/com/sparta/jwt/RefreshToken.java
  escape-core/src/main/java/com/sparta/jwt/RefreshTokenInfo.java
  escape-core/src/main/java/com/sparta/jwt/RefreshTokenRepository.java
  escape-core/src/main/java/com/sparta/jwt/RefreshTokenService.java
  escape-core/src/main/java/com/sparta/security/JwtAuthorizationFilter.java
  escape-core/src/main/java/com/sparta/security/ResponseUtil.java
  escape-core/src/main/java/com/sparta/security/filter/CustomAccessDeniedHandler.java
  escape-core/src/main/java/com/sparta/security/filter/CustomAuthenticationEntryPoint.java
  escape-core/src/main/java/com/sparta/security/filter/JwtAuthenticationFilter.java
  escape-core/src/main/java/com/sparta/security/filter/JwtAuthorizationFilter.java
  escape-manager/src/main/resources/application.yml
  http-test/UserTest.http
Labels: feature
